language: node_js
node_js:
  - "8.10"

branches:
only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - npm run packagr

after_success:
  - npm version patch
  - npm publish dist

notifications:
email:
  on_failure: change
  on_success: change
