language: node_js
node_js:
  - "8.10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - npm run packagr

before_deploy:
  - cd dist

deploy:
  provider: npm
  email: "tumit@live.com"
  skip_cleanup: true
  api_key: $NPM_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
